### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#26]
- [x]  AST that conforms to the ECMA specs

- [x]   TS / JS parser 

- [x]  Travers / walker

- [x]  Transformer API

- [x]  Public API to generate AST nodes

- [ ]  Grammar checker 

- [ ] Pretty printing

- [ ]  Linting

- [ ]  Minifier

**Comment by KFlash** [comment]
@aladdin-add Can you think about how we can  implement a grammar checker?

**Comment by KFlash** [comment]
Closing as outdated
